spring:
  datasource:
    url: jdbc:postgresql://localhost:45533/JwtTest
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true

server:
  port: 8443
  ssl:
    key-store: src\main\resources\javadevjournal.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: javadevjournal
